### PR TITLE
added state and removed need of loading page twice

### PR DESCRIPTION
**Pull request by kaiz123**

### CODE REVIEW

**Comment by atherdon** [comment]
lets discuss about changing the project structure. we used a create-react-app starter, but looks like you replace it with webpack + clean react+node installation. can you explain the reason?

**Comment by atherdon** [comment]
ok, good - because a lot of stuff that was installed - going by default inside `react-scripts`. You can read more about it here: https://github.com/facebook/create-react-app

**Comment by atherdon** [comment]
perfect. mergin

**Comment by kaiz123** [comment]
Package lock has changed

**Comment by kaiz123** [comment]
Fixing that give me a minute

**Comment by atherdon** [comment]
i think all was fine

**Pull request merged**
