### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by AminuSufi585**
I have set up a basic routing.

### CODE REVIEW

**Comment by atherdon** [comment]
@AminuSufi585 please make changes on this PR so i'll be able to merge it

**Comment by AminuSufi585** [comment]
Ok I have noted it since, developing locally. Next PR is coming soon.

**Comment by atherdon** [comment]
ok, glad to know. i'm preparing some updates, that will make a lot of things clear in our process.

**Comment by AminuSufi585** [comment]
This is great. Can't wait for it.

**Pull request merged**
